### ISSUE TITLE
's' and '8' in italics are defective in Normal width

### ISSUE THREAD

**Issue by cssobral2013** [productiontype/Georama#4]

**Comment by thlinard** [comment]
Black Italic?
<img width="543" alt="Georama" src="https://user-images.githubusercontent.com/13808824/91727742-65995b80-eba2-11ea-9c45-20355198e99a.png">

**Comment by cssobral2013** [comment]
Yes, mainly in this weight. I got an idea: why not add one more master, for
Normal width?

Em seg, 31 de ago de 2020 10:55 AM, Thomas Linard <notifications@github.com>
escreveu:

**Comment by productiontype** [comment]
The issue is tied with a support layer that was not taken into account upon generation. Happens in other styles as well. Will push a fix.

**Comment by davelab6** [comment]
@productiontype thanks! Please do increment the version number, that will help downstream propagation such as to Google Fonts
