### ISSUE TITLE
Some letters contain crossing anchor points, which give a problem when using the font for outlined text

### ISSUE THREAD

**Issue by kaspervdv** [productiontype/Georama#7]
Here you see the problem with the letter K.
<img width="1766" alt="Schermafbeelding 2022-04-19 om 11 05 29" src="https://user-images.githubusercontent.com/32158194/163970671-e048df12-d22f-4b63-8959-e15ff39f82c4.png">

**Comment by productiontype** [comment]
This behavior is due to variable fonts. In order to keep a consistent angle for the K legs we need to use overlapping outlines.
To get the expected behavior, you can either:
* convert your text to outlines and manually correct the K to the desired shape
* use static fonts
